Controllers/Brand_DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Electronic_MVC.Data;
using Electronic_MVC.Models;
using Microsoft.AspNetCore.Authorization;

namespace Electronic_MVC.Controllers
{
    public class Brand_DetailController : Controller
    {
        private readonly Electronic_MVCContext _context;

        public Brand_DetailController(Electronic_MVCContext context)
        {
            _context = context;
        }

        // GET: Brand_Detail
        public async Task<IActionResult> Index()
        {
            return View(await _context.Brand_Detail.ToListAsync());
        }

        // GET: Brand_Detail/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand_Detail = await _context.Brand_Detail
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand_Detail == null)
            {
                return NotFound();
            }

            return View(brand_Detail);
        }
        [Authorize]
        // GET: Brand_Detail/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Brand_Detail/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Brand_Name,Brand_Branch_Location,Brand_Email")] Brand_Detail brand_Detail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(brand_Detail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(brand_Detail);
        }
        [Authorize]
        // GET: Brand_Detail/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand_Detail = await _context.Brand_Detail.FindAsync(id);
            if (brand_Detail == null)
            {
                return NotFound();
            }
            return View(brand_Detail);
        }

        // POST: Brand_Detail/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Brand_Name,Brand_Branch_Location,Brand_Email")] Brand_Detail brand_Detail)
        {
            if (id != brand_Detail.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brand_Detail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Brand_DetailExists(brand_Detail.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand_Detail);
        }
        [Authorize]
        // GET: Brand_Detail/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand_Detail = await _context.Brand_Detail
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand_Detail == null)
            {
                return NotFound();
            }

            return View(brand_Detail);
        }

        // POST: Brand_Detail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brand_Detail = await _context.Brand_Detail.FindAsync(id);
            _context.Brand_Detail.Remove(brand_Detail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Brand_DetailExists(int id)
        {
            return _context.Brand_Detail.Any(e => e.Id == id);
        }
    }
}

Controllers/Order_DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Electronic_MVC.Data;
using Electronic_MVC.Models;
using Microsoft.AspNetCore.Authorization;


namespace Electronic_MVC.Controllers
{
    [Authorize]
    public class Order_DetailController : Controller
    {
        private readonly Electronic_MVCContext _context;

        public Order_DetailController(Electronic_MVCContext context)
        {
            _context = context;
        }

        // GET: Order_Detail
        public async Task<IActionResult> Index()
        {
            var electronic_MVCContext = _context.Order_Detail.Include(o => o.Customer_Detail).Include(o => o.Product_Detail);
            return View(await electronic_MVCContext.ToListAsync());
        }

        // GET: Order_Detail/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order_Detail = await _context.Order_Detail
                .Include(o => o.Customer_Detail)
                .Include(o => o.Product_Detail)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order_Detail == null)
            {
                return NotFound();
            }

            return View(order_Detail);
        }

        // GET: Order_Detail/Create
        public IActionResult Create()
        {
            ViewData["Customer_DetailId"] = new SelectList(_context.Customer_Detail, "Id", "Customer_Name");
            ViewData["Product_DetailId"] = new SelectList(_context.Product_Detail, "Id", "Product_Name");
            return View();
        }

        // POST: Order_Detail/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Quantity,Discount,Customer_DetailId,Product_DetailId")] Order_Detail order_Detail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order_Detail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Customer_DetailId"] = new SelectList(_context.Customer_Detail, "Id", "Customer_Name", order_Detail.Customer_DetailId);
            ViewData["Product_DetailId"] = new SelectList(_context.Product_Detail, "Id", "Product_Name", order_Detail.Product_DetailId);
            return View(order_Detail);
        }
        [Authorize]
        // GET: Order_Detail/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order_Detail = await _context.Order_Detail.FindAsync(id);
            if (order_Detail == null)
            {
                return NotFound();
            }
            ViewData["Customer_DetailId"] = new SelectList(_context.Customer_Detail, "Id", "Customer_Name", order_Detail.Customer_DetailId);
            ViewData["Product_DetailId"] = new SelectList(_context.Product_Detail, "Id", "Product_Name", order_Detail.Product_DetailId);
            return View(order_Detail);
        }

        // POST: Order_Detail/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Quantity,Discount,Customer_DetailId,Product_DetailId")] Order_Detail order_Detail)
        {
            if (id != order_Detail.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order_Detail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Order_DetailExists(order_Detail.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Customer_DetailId"] = new SelectList(_context.Customer_Detail, "Id", "Customer_Name", order_Detail.Customer_DetailId);
            ViewData["Product_DetailId"] = new SelectList(_context.Product_Detail, "Id", "Product_Name", order_Detail.Product_DetailId);
            return View(order_Detail);
        }

        // GET: Order_Detail/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order_Detail = await _context.Order_Detail
                .Include(o => o.Customer_Detail)
                .Include(o => o.Product_Detail)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order_Detail == null)
            {
                return NotFound();
            }

            return View(order_Detail);
        }

        // POST: Order_Detail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order_Detail = await _context.Order_Detail.FindAsync(id);
            _context.Order_Detail.Remove(order_Detail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Order_DetailExists(int id)
        {
            return _context.Order_Detail.Any(e => e.Id == id);
        }
    }
}

Controllers/Product_DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Electronic_MVC.Data;
using Electronic_MVC.Models;
using Microsoft.AspNetCore.Authorization;


namespace Electronic_MVC.Controllers
{
    public class Product_DetailController : Controller
    {
        private readonly Electronic_MVCContext _context;

        public Product_DetailController(Electronic_MVCContext context)
        {
            _context = context;
        }

        // GET: Product_Detail
        public async Task<IActionResult> Index()
        {
            var electronic_MVCContext = _context.Product_Detail.Include(p => p.Brand_Detail).Include(p => p.Category_Detail);
            return View(await electronic_MVCContext.ToListAsync());
        }

        // GET: Product_Detail/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product_Detail = await _context.Product_Detail
                .Include(p => p.Brand_Detail)
                .Include(p => p.Category_Detail)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product_Detail == null)
            {
                return NotFound();
            }

            return View(product_Detail);
        }
        [Authorize]
        // GET: Product_Detail/Create
        public IActionResult Create()
        {
            ViewData["Brand_DetailId"] = new SelectList(_context.Brand_Detail, "Id", "Brand_Name");
            ViewData["Category_DetailId"] = new SelectList(_context.Category_Detail, "Id", "Product");
            return View();
        }

        // POST: Product_Detail/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Product_Name,Price,Brand_DetailId,Category_DetailId")] Product_Detail product_Detail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product_Detail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Brand_DetailId"] = new SelectList(_context.Brand_Detail, "Id", "Brand_Name", product_Detail.Brand_DetailId);
            ViewData["Category_DetailId"] = new SelectList(_context.Category_Detail, "Id", "Product", product_Detail.Category_DetailId);
            return View(product_Detail);
        }
        [Authorize]
        // GET: Product_Detail/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product_Detail = await _context.Product_Detail.FindAsync(id);
            if (product_Detail == null)
            {
                return NotFound();
            }
            ViewData["Brand_DetailId"] = new SelectList(_context.Brand_Detail, "Id", "Brand_Name", product_Detail.Brand_DetailId);
            ViewData["Category_DetailId"] = new SelectList(_context.Category_Detail, "Id", "Product", product_Detail.Category_DetailId);
            return View(product_Detail);
        }

        // POST: Product_Detail/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Product_Name,Price,Brand_DetailId,Category_DetailId")] Product_Detail product_Detail)
        {
            if (id != product_Detail.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product_Detail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Product_DetailExists(product_Detail.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Brand_DetailId"] = new SelectList(_context.Brand_Detail, "Id", "Brand_Name", product_Detail.Brand_DetailId);
            ViewData["Category_DetailId"] = new SelectList(_context.Category_Detail, "Id", "Product", product_Detail.Category_DetailId);
            return View(product_Detail);
        }
        [Authorize]
        // GET: Product_Detail/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product_Detail = await _context.Product_Detail
                .Include(p => p.Brand_Detail)
                .Include(p => p.Category_Detail)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product_Detail == null)
            {
                return NotFound();
            }

            return View(product_Detail);
        }

        // POST: Product_Detail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product_Detail = await _context.Product_Detail.FindAsync(id);
            _context.Product_Detail.Remove(product_Detail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Product_DetailExists(int id)
        {
            return _context.Product_Detail.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Electronic Items</title>

    <!-- Site Icons -->
    <link rel="shortcut icon" href="~/images/favicon.ico" type="image/x-icon" />
    <link rel="apple-touch-icon" href="~/images/apple-touch-icon.png">

    <!-- Design fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.css" rel="stylesheet">

    <!-- FontAwesome Icons core CSS -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/style.css" rel="stylesheet">

    <!-- Responsive styles for this template -->
    <link href="~/css/responsive.css" rel="stylesheet">

    <!-- Colors for this template -->
    <link href="~/css/colors.css" rel="stylesheet">

    <!-- Version Tech CSS for this template -->
    <link href="~/css/version/tech.css" rel="stylesheet">

   
   
</head>
<body>
  
        <!--Header-->
        <header class="tech-header header">
            <div class="container-fluid">
                <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="tech-index.html"><img src="images/version/tech-logo.png" alt=""></a>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Brand_Detail" asp-action="Index">Brand</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category_Detail" asp-action="Index">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer_Detail" asp-action="Index">Customer</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product_Detail" asp-action="Index">Product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order_Detail" asp-action="Index">Order</a>
                            </li>
                        </ul>
                        <partial name="_LoginPartial" /><!--code to display the login and regiter pages-->

                    </div>
                </nav>
            </div><!-- end container-fluid -->
        </header><!-- end market-header -->

    <!--code of the container part-->
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

    <!--footer area -->
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - Electronic Items - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>

        </footer>

        <!-- Core JavaScript
    ================================================== -->
        <script src="~/js/jquery.min.js"></script>
        <script src="~/js/tether.min.js"></script>
        <script src="~/js/bootstrap.min.js"></script>
        <script src="~/js/custom.js"></script>


   
    @await RenderSectionAsync("Scripts", required: false)
       
</body>
</html>